# Generated by Django 4.0.1 on 2022-08-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_plan_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='plan',
        ),
    ]
