# Generated by Django 4.0.1 on 2022-08-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_deposit_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='option',
        ),
    ]
