# Generated by Django 4.0.1 on 2022-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_deposit_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='deposit',
        ),
    ]
